# Generated by Django 3.2.16 on 2022-12-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('Consumable', 'Consumable'), ('Peripheral', 'Peripheral')], max_length=100)),
                ('item_price', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
