# Generated by Django 3.2.16 on 2022-12-19 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_alter_item_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
    ]
