# Generated by Django 3.2.16 on 2022-12-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('Consumable', 'Consumable'), ('Peripheral', 'Peripheral')], max_length=100)),
                ('item_price', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
