# Generated by Django 3.2.16 on 2022-12-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costcentre', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=100)),
                ('isapprover', models.BooleanField(default=False, null=True, verbose_name='Is Approver?')),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('isapprover', models.BooleanField(default=False, null=True, verbose_name='Is Approver level I?')),
                ('isapprover_last', models.BooleanField(default=False, null=True, verbose_name='Is Approver Level II?')),
            ],
        ),
    ]
