# Generated by Django 3.2.16 on 2022-12-19 07:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='approvalcode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8)),
                ('condition', models.DecimalField(decimal_places=10, max_digits=19)),
                ('remarks', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='frequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=8, null=True)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(default='DELAYED', max_length=8, null=True)),
                ('submitted', models.DateField(default=datetime.date.today)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.employee')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.item')),
            ],
        ),
        migrations.CreateModel(
            name='cashapprover',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approverorder', models.IntegerField(null=True, verbose_name='Order')),
                ('remarks', models.CharField(max_length=50)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver', to='helpdesk.employee')),
                ('backupapprover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backupapprover', to='helpdesk.employee', verbose_name='Backup Approver')),
            ],
        ),
    ]
