# Generated by Django 3.2.16 on 2022-12-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0010_alllogin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crequest',
            options={'verbose_name': 'Cash_Request'},
        ),
        migrations.AlterModelOptions(
            name='frequest',
            options={'verbose_name': 'Form_Request'},
        ),
        migrations.AddField(
            model_name='employee',
            name='area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='isapprover',
            field=models.BooleanField(default=False, null=True, verbose_name='Is IT Approver?'),
        ),
    ]
