# Generated by Django 3.2.16 on 2022-12-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0011_auto_20221226_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='area',
            field=models.TextField(null=True),
        ),
    ]
