# Generated by Django 3.2.16 on 2022-12-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0012_alter_employee_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frequestdetail',
            name='prf_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
