# Generated by Django 3.2.16 on 2023-01-05 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0013_auto_20221227_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashapprover', to='helpdesk.employee', verbose_name='Approver Cash Adv'),
        ),
        migrations.AddField(
            model_name='employee',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.employee', verbose_name='Atasan'),
        ),
    ]
