# Generated by Django 3.2.16 on 2023-01-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0015_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('CONSUMABLES', 'CONSUMABLES'), ('PERIPHERAL', 'PERIPHERAL')], max_length=100),
        ),
    ]
