# Generated by Django 3.2.16 on 2023-01-08 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0016_alter_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='headposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.position', verbose_name='Atasan'),
        ),
    ]
