# Generated by Django 3.2.16 on 2023-02-20 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0017_position_headposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashapprover', to='helpdesk.employee', verbose_name='First Approver of Cash Adv'),
        ),
        migrations.AlterField(
            model_name='position',
            name='headposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.position', verbose_name='Head'),
        ),
        migrations.CreateModel(
            name='logemail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetrans', models.DateTimeField(auto_now_add=True)),
                ('timetrans', models.TimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('resendlink', models.CharField(max_length=100)),
                ('codelink', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
