# Generated by Django 3.2.16 on 2023-04-18 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0019_alter_logemail_resendlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailsent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetrans', models.DateTimeField(auto_now_add=True)),
                ('timetrans', models.TimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('resendlink', models.TextField(blank=True, null=True)),
                ('codelink', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.employee')),
            ],
        ),
    ]
