"""
Django settings for portal project.

Generated by 'django-admin startproject' using Django 2.1.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
#import pymysql


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '37rr#2y_ba9--%p6zm)sjk4!g-)owgd7*o-_(-5v=vmz*o8dc7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['emgmt.sinarmeadow.com']


# Application definition

INSTALLED_APPS = [ 
    'helpdesk',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  
    'django_filters',
    'import_export',  
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',

]

CSRF_COOKIE_SECURE = True 
SESSION_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = False

ROOT_URLCONF = 'portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'helpdesk/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'u8395097_smiportal',
    	'USER': 'u8395097_smihelpdesk',
    	'PASSWORD' : '7IG0Wr9nt,b#',
    	'HOST' : 'localhost',
    	'PORT': '3306',
        'CONN_MAX_AGE': None,
        'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"},
    }
}
'''
DATABASES = {
    'default': {
        'NAME': 'u8395097_smiportal', 
        'ENGINE': 'mysql.connector.django',
        'HOST': 'localhost',
        'PORT': 3306,
        'USER': 'u8395097_smihelpdesk',
        'PASSWORD': '7IG0Wr9nt,b#',
        'OPTIONS': {
          'autocommit': True,

        },
    },
    "other": {
        "ENGINE": "mysql.connector.django",
        "NAME": "u8395097_smiportal",
        "USER": "u8395097_smihelpdesk",
        "PASSWORD": "7IG0Wr9nt,b#",
        "HOST": "localhost",
        "PORT": 3306,
        "TEST_CHARSET": "utf8",
        "TEST_COLLATION": "utf8_general_ci",
        "TEST_MIRROR": "default",
        "TEST": {
            "CHARSET": "utf8",
            "COLLATION": "utf8_general_ci",
            "MIRROR": "default",
        },
    },
}


'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', 
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
'''

#pymysql.version_info = (1, 4, 2, 'final', 0)  # change mysqlclient version
#pymysql.install_as_MySQLdb()

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_L10N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
IMPORT_EXPORT_USE_TRANSACTIONS = True


DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

'''
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "helpdesk/static")
]
'''

LOGIN_URL='/loginPage'
LOGIN_REDIRECT_URL='/path/to/redirecturl'

'''
EMAIL_HOST = 'smtp.mailtrap.io'
EMAIL_HOST_USER = 'bfa64e6870a353'
EMAIL_HOST_PASSWORD = '792b17899147c2'
EMAIL_PORT = '2525'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'   
EMAIL_HOST = 'mail.sinarmeadow.com'
EMAIL_USE_SSL = True
#EMAIL_USE_TLS = True
EMAIL_PORT = 465
EMAIL_HOST_USER = 'mis@sinarmeadow.com'
EMAIL_HOST_PASSWORD = 'Smii3mgmt'

DEFAULT_FROM_EMAIL = 'mis@sinarmeadow.com'
SERVER_EMAIL = 'mail.sinarmeadow.com'
'''

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'   
EMAIL_HOST = 'mail.smii.co.id'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'emgmt@smii.co.id'
EMAIL_HOST_PASSWORD = 'Smii3mgmt'
EMAIL_FROM = '<emgmt@smii.co.id>'

#TIMEOUT 10 MENIT
SESSION_EXPIRE_SECONDS = 600
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_TIMEOUT_REDIRECT = '/loginPage' # Add your URL
SESSION_EXPIRE_AT_BROWSER_CLOSE=True # Invalid session

IMPORT_EXPORT_CHUNK_SIZE = 200

COMPANY_ADDRESS = '<p>PT. Sinar Meadow International Indonesia<br>Kawasan Industri Pulogadung, Jl Puloayang I No. 6<br>Jakarta 13260</p>'