# Generated by Django 3.2.16 on 2023-05-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emailschedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetrans', models.DateTimeField(auto_now_add=True)),
                ('timetrans', models.TimeField(auto_now=True)),
                ('messageBody', models.TextField(blank=True, null=True)),
                ('messageSubject', models.CharField(max_length=200)),
                ('fromEmail', models.CharField(max_length=100)),
                ('sendToEmail', models.CharField(max_length=50)),
                ('codelink', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('INITIAL', 'INITIAL'), ('SENT', 'SENT'), ('FAILED', 'FAILED'), ('TEST', 'TEST')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='emailSchedulesCtrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parameter', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False, null=True, verbose_name='Is Active?')),
            ],
        ),
    ]
